name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove old container
            docker rm -f flask-app || true

            # Free port 80 if it's being used
            PID=$(lsof -t -i:80)
            if [ ! -z "$PID" ]; then
              kill -9 $PID || true
            fi

            # Remove old Docker image if it exists
            IMAGE_ID=$(docker images -q flask-ci-cd)
            if [ ! -z "$IMAGE_ID" ]; then
              docker rmi -f $IMAGE_ID || true
            fi

            # Clone latest code
            rm -rf flask-ci-cd-aws
            git clone https://github.com/thebjm/flask-ci-cd-aws.git
            cd flask-ci-cd-aws

            # Build new Docker image
            docker build -t flask-ci-cd .

            # Run the container on port 80 -> container port 5000
            docker run -d -p 80:5000 --name flask-app flask-ci-cd
