name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf flask-ci-cd-aws
            git clone https://github.com/thebjm/flask-ci-cd-aws.git
            cd flask-ci-cd-aws
            docker rm -f flask-app || true
            docker rmi flask-ci-cd || true
            docker build -t flask-ci-cd .
            docker run -d -p 80:5000 --name flask-app flask-ci-cd
