name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd flask-ci-cd-aws || git clone https://github.com/thebjm/flask-ci-cd-aws.git && cd flask-ci-cd-aws
          git pull origin master
          docker rm -f flask-app || true
          docker rmi flask-ci-cd || true
          docker build -t flask-ci-cd .
          docker run -d -p 80:5000 --name flask-app flask-ci-cd
        EOF
